package com.meng.SeeMeMove;

import com.meng.AccelerometerExample.R;

import android.app.Activity;
import android.content.Context;
import android.content.res.Configuration;
import android.location.Criteria;
import android.location.GpsStatus;
import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import android.os.Bundle;
import android.os.PowerManager;
import android.view.KeyEvent;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.TextView;
import android.widget.Toast;
 
/**
 * @author	Richard Flanagan
 * @version	1.7 This is the 7th iteration of the code
 * @since	2012-03-28
 */
public class SeeMeMoveActivity extends Activity implements SeeMeMoveHandler {
 
    private static Context CONTEXT;	
    private LocationManager locationManager;
	private String provider;
	private WebView webView;
    
    /** Called when the activity is first created. */
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.main);
        CONTEXT = this;
        
        // CHECK USER HAS INTERNET CONNECTION
		if(!haveNetworkConnection()) {
			// TODO Validate Internet connection and pass message to user
		}
		else {
			if(AccelerometerHandler.accIsSupported())
	            AccelerometerHandler.startToListen(this);
		}		 
		
		/*
		 * CURRENT UI GENERATED HERE!!!! 
		 */
		webView = (WebView) findViewById(R.id.webView1);
		webView.setWebViewClient(new twitWebViewClient());
		webView.getSettings().setJavaScriptEnabled(true);
		webView.getSettings().setSupportZoom(true);
		webView.loadUrl("http://demo.papaonlegs.s1.goincloud.com/seememove.html");
    }
    
    /** Allow user to use back key*/
//    public boolean onKeyDown(int keyCode, KeyEvent event){
//    	
//    	if((keyCode == KeyEvent.KEYCODE_BACK) && webView.canGoBack()){
//    		webView.goBack();
//    		return true;
//    	}
//    	return super.onKeyDown(keyCode, event);
//    }
    
    /** Called when the activity UI appears to user. */
    @Override
    public void onStart() {
    	super.onStart();
    	
    	/** GPS Stuff */
    	Criteria criteria = new Criteria();
    	criteria.setAccuracy(Criteria.ACCURACY_FINE);
    	criteria.setBearingRequired(true);
    	criteria.setCostAllowed(true);
    	criteria.setPowerRequirement(Criteria.POWER_LOW);
    	criteria.setAltitudeRequired(false);
    	locationManager = (LocationManager) getSystemService(LOCATION_SERVICE);
    	locationManager.addGpsStatusListener(gpsStatusListener);
    	provider = locationManager.getBestProvider(criteria, true);
    	locationManager.requestLocationUpdates(provider, 2, 10000, AccelerometerHandler.locationListener);    	
    }
    
    protected void onResume() {
        super.onResume();
    }
    
    /** Deactivates the the Accelerometer Sensors when application 
     *  is closed or brought to background
     */
    protected void onDestroy() {
        super.onDestroy();
        if(AccelerometerHandler.isListening()) {
            AccelerometerHandler.stopListening();
        }
    }
    
    @Override
    public void onConfigurationChanged(Configuration newConfig){        
        super.onConfigurationChanged(newConfig);
    }
 
    public static Context getContext() {
        return CONTEXT;
    }
    
    /**
     * onStopListening callback method to pass accelerometer 
     * sensor status information to the UI  
     */
    public void onStopAccelerometerListening() { }
 
    /**
     * postData callback method to pass accelerometer data information  
     * to the UI 
     * 
     * DEFUNCT USED FOR TESTING
     * 
     * @param accData string data that can be presented on the UI
     * @return void
     */
    public void getSomeData(final String accData) {        
    	 /**CAN BE USED TO PASS INFORMATION GENERATED BY THE SeeMeMoveTools 
    	  *	SeeMeMoveTools OBJECT TO BE USED IN THE UI 
    	  */	 
    	Toast.makeText(SeeMeMoveActivity.CONTEXT, "DATA SENT | Average: " + accData, 4000).show();    
    }
      
	/**
     * onAccelerationChanged callback method to pass accelerometer data 
     * to the UI
     * 
     * DEFUNCT USED FOR TESTING
     * 
     * @param 	x 	x plane accelerometer data
     * @param 	y	y plane accelerometer data
     * @param	z	z plane accelerometer data
     * @return void
     */
    public void onAccelerationChanged(float x, float y, float z) {
    	 /**CAN BE USED TO PASS INFORMATION GENERATED BY THE SeeMeMoveTools 
    	  * OBJECT TO BE USED IN THE UI  
    	  */
    }
	
    /**
     * Method for establishing if this devise has an Internet connection
     * 
     * @return boolean
     */
	private boolean haveNetworkConnection() {
	    boolean haveConnectedWifi = false;
	    boolean haveConnectedMobile = false;

	    ConnectivityManager connectionManager = (ConnectivityManager) getSystemService(Context.CONNECTIVITY_SERVICE);
	    NetworkInfo[] netInfo = connectionManager.getAllNetworkInfo();
	    for (NetworkInfo ni : netInfo) {
	        if (ni.getTypeName().equalsIgnoreCase("WIFI"))
	            if (ni.isConnected())
	                haveConnectedWifi = true;
	        if (ni.getTypeName().equalsIgnoreCase("MOBILE"))
	            if (ni.isConnected())
	                haveConnectedMobile = true;
	    }
	    return haveConnectedWifi || haveConnectedMobile;
	}
	
	/** GPS Stuff */
    GpsStatus.Listener gpsStatusListener = new GpsStatus.Listener() {		
		@Override
		public void onGpsStatusChanged(int event) {	
		}
	}; 
	
	private class twitWebViewClient extends WebViewClient {
		@Override
		public boolean shouldOverrideUrlLoading(WebView view, String url) {
			view.loadUrl(url);
			return true;
		}
	}
}